version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    environment:
      - DISPLAY=:1
    ports:
      - 6080:6080
    command: /usr/local/bin/start-vnc.sh
